### ISSUE TITLE
Integration version 2.0

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/XiaomiGateway3#527]
- [x] Support Aqara E1 Door & Window Sensor (MCCGQ14LM) #522 
- [x] Support Xiaomi TH model XMWSDJ04MMC (BLE) #490 
- [x] Support Mosquitto Mesh WX10ZM #408
- [x] Support FlexSwitch setting #355 
- [x] Support Aqara Relay Intelock #68
- [x] Support Aqara Cube sides #475 
- [x] Support Sonoff TH1 #528
- [x] Support Sonoff Door sensor with wrong model
- [x] Support Aqara H1 EU switches with neutral #537
- [x] Better support Aqara Lock S2 Pro #143 
- [x] Better support Aqara Lock S2 #551
- [x] Support entity categorization #502 
- [x] Support temp sensors of plugs #59
- [x] Support zigbee binding
- [x] Support binding for Aqara Opple
- [x] Support unlisted zigbee devices
- [x] Adds switch to light conversion #108
- [x] Adds internal available logic #515
- [x] Fix `attributes_template` #525 
- [x] Fix old mosquitto_pub process #501 
- [x] Fix Xiaomi Illumination sensor #531
- [x] Fix rename entity issue #539 
- [x] Check reconnection logic #530
- [x] Support remove BLE devices
- [x] Troubleshooting docs section
- [x] Fix unavailable for lazy converters (eg BLE)
- [x] Rename ADV options to DANGER

**Comment by vturekhanov** [comment]
There is "Zigbee Remove" command in the _command entity. It deletes a zigbee device. Could you please also add ability to delete BLE and MESH devices?

**Comment by rbron01** [comment]
HI I am missing the _zigbee entities is this feature depreciated?
Also I do not see how to switch them on anymore.

**Comment by guardianbs** [comment]
Hi, the _Zigbee and _ble entities used to be created automatically. If these are now optional how do you turn them on ?

Also is there any documentation on the functionality made available by the new hub Command / Data feature

**Comment by sephrioth** [comment]
Somehow 'delete' device function doesn't work.  It just rename device to 'delete'.

**Comment by AlexxIT** [comment]
Rename with delete was deprecated. Will return it later
